### ISSUE TITLE
How to update job status in Sauce Labs

### ISSUE THREAD

**Issue by danieltisdale** [Percona-Lab/codeceptjs-saucehelper#2] opened 2019-03-19 18:43 UTC
Hi,

I have just installed the codeceptjs-saucehelper and I am getting some output from the sauce-helper, but I am not getting the job status to be correctly passed through. How do I configure my tests to use this helper?

Here's the output from my terminal when I run a test:

```HomePage --
  ✔ User can navigate to the buy page from the homepage @smoke in 68608ms
Test has Passed
Test finished. Link to job: https://saucelabs.com/jobs/decb7bf6029543b8bae3c06508b38849
undefined

**Comment by puneet0191** [comment] 2019-03-20 05:47
@danieltisdale the problem is, you are missing sauce_user and sauce_key in your configuration of the helper, check the updated readme on how to set the configuration for the helper: https://github.com/Percona-Lab/codeceptjs-saucehelper/blob/master/readme.md

**Comment by lokesh-rj** [comment] 2019-03-20 12:40
Hello,
I have added Sauce Helper to my codecept.json file.
And, I cannot see job names being updated to sauce labs.
Also,
I got below error-

TypeError: Cannot read property 'sessionID' of undefined

Helpers snippet of my codecept.json file.

"helpers": {
    "WebDriverIO": {
      "url": "https://",
      "browser": "chrome",
      "host": "ondemand.saucelabs.com",
      "port": 443,
      "user": "username",
      "key": "sauce-key"
    },
    "SauceHelper": {
      "require": "codeceptjs-saucehelper",
      "user": "username",
      "key": "sauce-userkey"
    }
  },

**Comment by puneet0191** [comment] 2019-03-20 15:38
@lokeshJR  could you please share the test code with me?

**Comment by lokesh-rj** [comment] 2019-03-20 15:54
Hi @puneet0191 ,

Below is my sample test script.

I am using page objects.

Feature('Digital Automation- Join Flow for AZ with AR');
Scenario('Enter And Submit Zipcode', (I, config, zipcodePage,chooseaplanPage) => {
    I.amOnPage(zipcodePage.path);
    I.waitForElement(zipcodePage.fields.zipcode,15);
    I.waitForElement(zipcodePage.buttons.go,25);
    zipcodePage.enterAndSubmitZipCode(config.zipcodeDetails.zipcode);
    //I.amOnPage(chooseaplanPage.path);
    I.waitForElement(chooseaplanPage.headerText.chooseAMembershipPlan,10);
    I.seeElement(chooseaplanPage.labels.aaaClassic);
    I.seeElement(chooseaplanPage.labels.aaaPlus);
    I.seeElement(chooseaplanPage.labels.aaaPremier);
    
}); 

please let me know, if you require any other information.

**Comment by puneet0191** [comment] 2019-03-21 07:28
hmm, not sure what could be the problem..where you able to launch the browser in sauce labs with that config? seems to not work for me

**Comment by lokesh-rj** [comment] 2019-03-21 09:56
Hi @puneet0191 ,

Tests are getting executed in Sauce labs  successfully. The thing is, the tests don't have a name.

PFB the screenshots.

![TypeError](https://user-images.githubusercontent.com/45636243/54744634-87d92c80-4bed-11e9-8a91-83d6e1146590.PNG)
![unnamedjob](https://user-images.githubusercontent.com/45636243/54744651-8f003a80-4bed-11e9-9dff-a5de579907bf.PNG)




It would be a great help, if you can provide a working/sample example about the sauce-helper?

**Comment by textbook** [comment] 2019-03-21 11:28
That must be coming from [this line][1]:

```javascript
return this.helpers['WebDriverIO'].browser.requestHandler.sessionID;
```

Do you see any warnings/errors around your versions of `webdriverio`? I think 4.x and the associated `WebDriverIO` helper are deprecated now, might be worth upgrading to 5.x, switching to the `WebDriver` helper and seeing if the problem persists.

  [1]: https://github.com/Percona-Lab/codeceptjs-saucehelper/blob/master/index.js#L82

**Comment by lokesh-rj** [comment] 2019-03-21 11:50
Hi @textbook ,

This is working, after switching to the WebDriver helper.

Thanks a lot for the help.

**Comment by puneet0191** [comment] 2019-03-25 06:45
Closing thanks

**Closed as completed by puneet0191** 2019-03-25 06:45 UTC
